import { Poetsen_One, Poppins } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';

const poetsenOne = Poetsen_One({
  variable: '--font-poetsen-one',
  subsets: ['latin'],
  weight: '400',
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '600'],
});

export const metadata = {
  title: 'DevTrainer',
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  description: 'Generated by Pirate',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${poetsenOne.variable} ${poppins.variable} antialiased bg-[#292929] text-white pt-24 px-5`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
